dbmgmt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='Admin'),
    path('', include('hospital.urls'))
]

hospital/urls.py
from django.urls import path
from hospital.views import home_view
from hospital.views import people_view
from hospital.views import medication_view
from hospital.views import consutation_view
from hospital.views import surgery_view
from hospital.views import perscription_view
from hospital.views import bed_view
from hospital.views import skill_view


urlpatterns = [
    path('', home_view.home_view , name='hospital-home'),
    # Patient Create/List/Detail
    path('create_patient', people_view.PatientCreateView.as_view(template_name="create_form.html") , name='create_patient_view'),
    path('list_patient.html', people_view.PatientListView.as_view(template_name="patient_list.html") , name='list_patient_view'),
    path('detail_patient/<pk>', people_view.PatientDetailView.as_view(template_name="patient_detail.html") , name='detail_patient_view'),
    # Medication
    path('create_medication.html', medication_view.MedicationCreateView.as_view(template_name="create_form.html"), name='create_medication_view'),
    path('medication_interaction.html', medication_view.CreateMedicationInteraction.as_view(template_name="create_form.html"), name='create_medication_interaction'),
    path('view_medications.html/<int:pk>/', medication_view.MedicationDetailView.as_view(), name='view_medications'),
    path('view_medications.html', medication_view.MedicationListView.as_view(), name='view_medications'),
    # Consultations
    path('create_consultation', consutation_view.ConsultationCreateView.as_view(template_name="create_form.html"), name='create_consultation_view'),
    path('view_consultation/<int:pk>/', consutation_view.ConsultationDetailView.as_view(template_name="consultation_detail.html"), name='detail_consultation_view'),
    path('list_consultation', consutation_view.ConsultationListView.as_view(template_name="consultation_list.html"), name='list_consultation_view'),
    # Surgeries
    path('create_surgery', surgery_view.SurgeryCreateView.as_view(template_name="create_form.html"), name='create_surgery_view'),
    path('view_surgery/<int:pk>/', surgery_view.SurgeryDetailView.as_view(template_name="surgery_detail.html"), name='detail_surgery_view'),
    path('list_surgery', surgery_view.SurgeryListView.as_view(template_name="surgery_list.html"), name='list_surgery_view'),
    # Perscriptions
    path('create_perscription', perscription_view.PerscriptionCreateView.as_view(template_name="create_form.html"), name='create_perscription_view'),
    path('view_perscription/<int:pk>/', perscription_view.PerscriptionDetailView.as_view(template_name="perscription_detail.html"), name='detail_perscription_view'),
    path('list_perscription', perscription_view.PerscriptionListView.as_view(template_name="perscription_list.html"), name='list_perscription_view'),
    # Beds/units
    path('list_bed_room_unit', bed_view.UnitListView.as_view(template_name="bed_room_unit_list.html"), name='list_bed_room_unit_view'),
    path('view_bed/<int:pk>', bed_view.assign_bed, name='detail_bed_view'),
    # Staff
    path('manage_physicians', people_view.ManagePhysicians.as_view(template_name="manage_physicians.html"), name='manage_physicians_view'),
    path('manage_surgeons', people_view.ManageSurgeons.as_view(template_name="manage_surgeons.html"), name='manage_surgeons_view'),
    path('manage_nurses', people_view.ManageNurses.as_view(template_name="manage_nurses.html"), name='manage_nurses_view'),
    # Staff Create
    path('create_physician', people_view.PhysicianCreateView.as_view(template_name="create_form.html"), name='create_physician_view'),
    path('create_surgeon', people_view.SurgeonCreateView.as_view(template_name="create_form.html"), name='create_surgeon_view'),
    path('create_nurse', people_view.NurseCreateView.as_view(template_name="create_form.html"), name='create_nurse_view'),
    path('view_physician/<pk>', people_view.PhysicianDetailView.as_view(template_name="physician_detail.html"), name='detail_physician_view'),
    path('view_surgeon/<pk>', people_view.SurgeonDetailView.as_view(template_name="surgeon_detail.html"), name='detail_surgeon_view'),
    path('view_nurse/<pk>', people_view.NurseDetailView.as_view(template_name="nurse_detail.html"), name='detail_nurse_view'),
    # Create/assign skill
    path('assign_skill/<pk>', skill_view.AssignedSkillCreateView.as_view(template_name="create_form.html"), name='add_skill_view'),
    # Add a staff member to patients
    path('add_staff/<pk>/', people_view.AddStaffToPatient.as_view(template_name="create_form.html"), name='staff_to_patient'),

]

hospital/models/base_model.py
class ShowAllDetailsMixin:
    """ Adds a get fields method to show all details in detail view"""
    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field
            in self.__class__._meta.fields
        ]

hospital/models/skill_types.py
""" Skills and types
- Surgeons have skills
- A Surgery has a SurgeryType made of skills
- If a surgeon has all those skills, he can perform it
"""
from django.db import models

from hospital import constants

class Skills(models.Model):
    """ The db containing all skills people can have
    New skills can be added but to avoid hard coding in constants
    """
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name


class SurgeryType(models.Model):
    """
    Defines a type of surgery and what skills are needed by the surgeon to complete it
    Nurses will also have one of these types assigned to them but don't need to worry
    about specific skills
    """
    name = models.CharField(max_length=50)
    requirements = models.ManyToManyField("Skills")

    def __str__(self) -> str:
        reqs = [r.name for r in self.requirements.all()]
        return f"{self.name} - {reqs}"


class AssignedSkills(models.Model):
    """ Links up what surgeons have what skills """
    # All skilled persons can have skills
    # nurses, surgeons need skills to perform surgeries

    class Meta:
        unique_together = ('person', 'skill')

    person = models.ForeignKey(
        "SkilledPerson",
        on_delete=models.CASCADE, # Delete skill link if person gone
    )
    skill = models.ForeignKey(
        "Skills",
        on_delete=models.CASCADE # Delete this entry if skill removed
    )

    def __str__(self) -> str:
        return f"{self.person.last_name}, {self.person.first_name} - {self.skill.name}"

hospital/forms/base_form.py
from django.forms import ModelForm


class BootstrapForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(BootstrapForm, self).__init__(*args, **kwargs)

        # you can iterate all fields here
        for _, f in self.fields.items():
            f.widget.attrs['class'] = 'form-control'

hospital/forms/bed_form.py
from django import forms
from hospital.models.places import Bed, Unit
from hospital.forms.base_form import BootstrapForm


class BedForm(BootstrapForm):
    class Meta:
        model = Bed
        fields = [
            'bed_letter',
            'room',
        ]

class UnitForm(BootstrapForm):
    class Meta:
        model = Unit
        fields = [
            'name',
            'prefix',
        ]

hospital/forms/consultation_form.py
from django import forms
from hospital.models.actions import Consultation
from hospital.forms.base_form import BootstrapForm


class ConsultationForm(BootstrapForm):
    class Meta:
        model = Consultation
        fields = [
            'physician',
            'patient',
            'date',
        ]

hospital/forms/medication_form.py
from django import forms
from hospital.models.illnesses import Medication, Interactions
from hospital.forms.base_form import BootstrapForm


class MedicationForm(BootstrapForm):
    class Meta:
        model = Medication
        fields = [
            'code',
            'name',
            'available_qnty',
            'cost',
            'usage'
        ]

    
class InteractionForm(BootstrapForm):
    medication1 = forms.ModelChoiceField(queryset= Medication.objects.all())
    medication2 = forms.ModelChoiceField(queryset= Medication.objects.all())
    class Meta:
        model = Interactions
        fields = [
            'medication1',
            'medication2',
            'severity'
        ]
        

hospital/forms/perscription_form.py
from django import forms
from hospital.models.actions import Perscriptions
from hospital.forms.base_form import BootstrapForm


class PerscriptionForm(BootstrapForm):
    class Meta:
        model = Perscriptions
        fields = [
            'physician',
            "patient",
            "medication",
            "frequency",
            "dosage",
        ]

hospital/forms/skill_form.py
from django import forms
from hospital.models.skill_types import AssignedSkills
from hospital.forms.base_form import BootstrapForm


class AssignedSkillsForm(BootstrapForm):
    class Meta:
        model = AssignedSkills
        fields = [
            'person',
            'skill',
        ]

hospital/views/bed_view.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

from hospital.forms.bed_form import BedForm
from hospital.models.places import Bed, Unit
from hospital.models.people import Patient, Nurse

class UnitListView(ListView):
    """ Basic List View to show BedListView """

    # specify the model for list view
    model = Unit

    def get_queryset(self, *args, **kwargs):
        """ Do any orders, filters, etc """
        qs = super(UnitListView, self).get_queryset(*args, **kwargs)
        # qs = qs.order_by("last_name")
        return qs


class BedListView(ListView):
    """ Basic List View to show BedListView """

    # specify the model for list view
    model = Bed

    def get_queryset(self, *args, **kwargs):
        """ Do any orders, filters, etc """
        qs = super(BedListView, self).get_queryset(*args, **kwargs)
        # qs = qs.order_by("last_name")
        return qs


def assign_bed(request, pk):
    if request.method=="GET":
        bed = Bed.objects.get(id=pk)
        # Get eligable patients
        return render(
            request,
            "bed_detail.html",
            {
                "bed": bed,
                "patients": Patient.objects.all(),
                "nurses": Nurse.objects.all()
            }
        )

    else:
        # Get ids from post
        patient_id = request.POST.get("patient_id")
        bed_id = request.POST.get("bed_id")
        nurse_id = request.POST.get("nurse_id")
        # Get objects from ids
        patient = Patient.objects.get(emp_number=patient_id)
        nurse = Nurse.objects.get(emp_number=nurse_id)
        bed = Bed.objects.get(id=bed_id)

        # Assign to patient
        patient.bed = bed
        patient.assigned_nurse = nurse
        patient.save()

        return redirect(reverse("list_bed_room_unit_view"))

class BedDetailView(DetailView):
    model = Bed

hospital/views/consutation_view.py
from django.urls import reverse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

from hospital.forms.consultation_form import ConsultationForm
from hospital.models.actions import Consultation

class ConsultationListView(ListView):
    """ Basic List View to show consultations """

    # specify the model for list view
    model = Consultation

    def get_queryset(self, *args, **kwargs):
        """ Do any orders, filters, etc """
        qs = super(ConsultationListView, self).get_queryset(*args, **kwargs)
        # qs = qs.order_by("last_name")
        return qs

class ConsultationDetailView(DetailView):
    model = Consultation

class ConsultationCreateView(CreateView):
    model = Consultation
    form_class = ConsultationForm

    def get_success_url(self):
        return reverse('detail_consultation_view', kwargs={'pk': self.object.id})

hospital/views/home_view.py
from django.shortcuts import render
from hospital.models.people import Physician, Patient, Nurse, Surgeon

# Create your views here.

def home_view(request):
    counts = {
        "physicians": Physician.objects.all(),
        "surgeons": Surgeon.objects.all(),
        "nurses": Nurse.objects.all(),
        "patients": Patient.objects.all(),
    }
    return render(request, 'home.html', counts)

hospital/views/medication_view.py
from django.shortcuts import render
from django.urls import reverse
from hospital.forms.medication_form import MedicationForm, InteractionForm
from django.shortcuts import redirect, render
from django.contrib import messages
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from hospital.models.illnesses import Medication, Interactions

# To add a new medication
class MedicationCreateView(CreateView):
    model = Medication
    form_class = MedicationForm

    def get_success_url(self):
        return reverse('view_medications', kwargs={'pk': self.object.id})


# class based view to view medications
class MedicationListView(ListView):
    model = Medication
    template_name = 'medication_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # count interactions and add them to context
        for object in context['object_list']:
            interactions_count = (
                Interactions.objects.filter(medication1=object.id ).count() +
                Interactions.objects.filter(medication2=object.id ).count() 
                )
            object.interactions_count = interactions_count
        return context


# detail view for each medication to show medication details and medicaiton interactions
class MedicationDetailView(DetailView):
    model = Medication
    template_name = 'Medication_detail_view.html'

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)

        # get list of interactions while shown medication is in medication1 of th table
        interacts_left = Interactions.objects.filter(medication1_id = self.kwargs['pk'])

        # get list of interactions while shown medication is in medication2 of th table
        interacts_right = Interactions.objects.filter(medication2_id = self.kwargs['pk'])

        # append interacting medications data
        interacts_with = []
        for interaction in interacts_left:
            interacts_with.append([interaction.medication2.id, interaction.medication2.code, 
                                   interaction.medication2.name , interaction.get_severity_display()])
        for interaction in interacts_right:
            interacts_with.append([interaction.medication1.id, interaction.medication1.code, 
                                   interaction.medication1.name , interaction.get_severity_display()])
        
        context ['interactions'] = interacts_with
        return context
    


# To add interaction between medications

class CreateMedicationInteraction(CreateView):
    model = Interactions
    form_class = InteractionForm

    def form_valid(self, form):
        if ( form.cleaned_data['medication1'] == form.cleaned_data['medication2'] ):
            form.add_error('medication2' ,"Can't add interaction to the same medication")
            return super().form_invalid(form)
        elif(Interactions.objects.filter(medication1 = form.cleaned_data['medication1'], 
                                         medication2 = form.cleaned_data['medication2']).exists() or
             Interactions.objects.filter(medication1 = form.cleaned_data['medication2'], 
                                         medication2 = form.cleaned_data['medication1']).exists()
                                           ):
            messages.error(self.request, "Interactin already exists")
            return super().form_invalid(form)
            
        messages.success(self.request, "Interaction has been saved")
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('create_medication_interaction')

hospital/views/perscription_view.py
from django.urls import reverse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

from hospital.forms.perscription_form import PerscriptionForm
from hospital.models.actions import Perscriptions


class PerscriptionListView(ListView):
    """ Basic List View to show Perscription """

    # specify the model for list view
    model = Perscriptions

    def get_queryset(self, *args, **kwargs):
        """ Do any orders, filters, etc """
        qs = super(PerscriptionListView, self).get_queryset(*args, **kwargs)
        # qs = qs.order_by("last_name")
        return qs

class PerscriptionDetailView(DetailView):
    model = Perscriptions

class PerscriptionCreateView(CreateView):
    model = Perscriptions
    form_class = PerscriptionForm

    def get_success_url(self):
        return reverse('detail_perscription_view', kwargs={'pk': self.object.id})

hospital/templates/Medication_detail_view.html
{% extends "base.html" %}
{% load static %}

{% block header %}
{{ header }}

{% endblock %}


{% block content %}
           <div class="list-group">
                <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1 text-primary">{{ object.name }}</h5>
                <small>Available Quantity: {{ object.available_qnty }} </small>
            </div>
            <p class="mb-1">Code: {{ object.code }}</p>
            <small>{{ object.usage }}</small>
            <h5></h5>
            <h5></h5>
            {% if interactions %}
                <h6>Interacts with </h6>
                <table class = "table">
                    <tr>
                        <th> Code </th>
                        <th> Name </th>
                        <th> Severity </th>
                    </tr>
                    {% for interaction in interactions %}
                        <tr>
                            <td>
                                <a href="{% url 'view_medications' interaction.0 %}" > 
                                {{ interaction.1 }}
                                </a>
                            </td> 
                            <td>  {{ interaction.2 }}</td>
                        <td>  {{ interaction.3 }}</td>  
                        </tr>
                    {% endfor %}
                {% endif %}
            </table>
               
        </div>

{% endblock %}

hospital/templates/bed_detail.html
{% extends "base.html" %}
{% load static %}

{% block header %}
{{ header }}

{% endblock %}



{% block content %}
<div class="container">
    <h1>Bed {{ bed.bed_code }}</h1>

    <div>
        {% comment %} PATIENT INFO {% endcomment %}
        <table class="table">
            <tr>
                <td>Bed Unit</td><td>{{ bed.room.unit.name }}</td>
            </tr>
            <tr>
                <td>Room</td><td>{{ bed.room.number }}</td>
            </tr>
            <tr>
                <td>Bed Letter</td><td>{{ bed.bed_letter }}</td>
            </tr>
        </table>
    </div>
    <div>
        <form method="POST" action="{% url "detail_bed_view" bed.id %}">
            {% csrf_token %}

            <div class="form-group">
                <input type="hidden" name="bed_id" value={{ bed.id }}>

                <div class="row">
                    <div class="col-sm-6">
                        <label for="patient-select">Choose Patient</label>
                        <select name="patient_id" class="form-control" id="patient-select">
                            {% for patient in patients %}
                            <option value={{ patient.emp_number }}>{{ patient.last_name }}, {{ patient.first_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-sm-6">
                        <label for="nurse-select">Choose Nurse</label>
                        <select name="nurse_id" class="form-control" id="nurse-select">
                            {% for nurse in nurses %}
                            <option value={{ nurse.emp_number }}>{{ nurse.last_name }}, {{ nurse.first_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

            </div>

            <div class="form-group">
                <button class="btn btn-primary mt-2" type="submit">Assign</button>
            </div>

        </form>
    </div>

</div>
{% endblock %}

hospital/templates/consultation_detail.html
{% extends "base.html" %}
{% load static %}

{% block header %}
{{ header }}

{% endblock %}



{% block content %}
<div class="container">
    <h1>Consultation on {{ object.date }}</h1>
    <div class="row">
        <div class="col-sm-6">
            {% comment %} PATIENT INFO {% endcomment %}
            <table>
                {% for label, value in object.patient.get_fields %}
                    <tr>
                        <td>{{ label }}</td>
                        <td>{{ value }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-sm-6">
            {% comment %} Pyhsician INFO {% endcomment %}
            <table>
                {% for label, value in object.physician.get_fields %}
                    <tr>
                        <td>{{ label }}</td>
                        <td>{{ value }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

</div>
{% endblock %}

hospital/templates/create_form.html
{% extends "base.html" %}
{% load static %}

{% block header %}
{{ header }}

{% endblock %}



{% block content %}
<div class="container">
    {% if messages %}
        {% for message in messages %}
        <div class = "container-fluid p-0">
            <div class= "alert {{ message.tags }}" role="alert">
                {{ message }}
            </div>
        </div>
        {% endfor %}
    {% endif %}

    <form id="the-form" method="POST" action="{{ post_to }}">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_table }}
        </div>
        <button type="submit" class="btn btn-primary mt-2">Submit</button>
    </form>
</div>
{% endblock %}

hospital/templates/manage_nurses.html
{% extends "base.html" %}
{% load static %}

{% block header %}
    <div class="">
        <h1>Manage Nurses</h1>
    </div>
{% endblock %}



{% block content %}
<div class="container">

        <!-- Iterate over object_list -->
        <table class="table">
            <tr>
                <th>Name</th>
                <th class="text-center">Grade</th>
                <th class="text-center">Experience(years)</th>
                <th class="text-center">Assigned Patients</th>
                <th class="text-center">Surgeries</th>
                <th class="text-center">Medical Record</th>

            </tr>
            {% for Nurse in object_list %}
            <tr>
                <td><a href="{% url "detail_nurse_view" Nurse.emp_number %}">{{ Nurse.last_name }}, {{ Nurse.first_name }}</a></td>
                <td class="text-center"> {{ Nurse.grade }} </td>
                <td class="text-center"> {{ Nurse.years_of_experience }} </td>
                <td class="text-center"> {{ Nurse.patients }} </td>
                <td class="text-center"> {{ Nurse.surgeries }} </td>
                {% if Nurse.isPatient %}
                <td class="text-center"><a href="{% url "detail_patient_view" Nurse.emp_number %}">View Record</a></td>
                {% else %}
                    <td class="text-center"> No Record, <a href="{% url "staff_to_patient" Nurse.emp_number %}"> Add </a></td>
                {% endif %}
            </div>
            </tr>
            {% endfor %}
        </table>

</div>
{% endblock %}

hospital/templates/manage_surgeons.html
{% extends "base.html" %}
{% load static %}

{% block header %}
    <div class="">
        <h1>Manage Surgeons</h1>
    </div>
{% endblock %}



{% block content %}
<div class="container">

        <!-- Iterate over object_list -->
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Speciality</th>
                <th class="text-center">Scheduled Surgeries</th>
                <th class="text-center">Contract Type</th>
                <th class="text-center">Medical Record</th>

            </tr>
            {% for surgeon in object_list %}
            <tr>
                <td><a href="{% url "detail_surgeon_view" surgeon.emp_number %}">{{ surgeon.last_name }}, {{ surgeon.first_name }}</a></td>
                <td> {{ surgeon.specialty }} </td>
                <td class="text-center"> {{ surgeon.surgeries }} </td>
                <td class="text-center"> {{ surgeon.contract_type }} </td>
                {% if surgeon.isPatient %}
                <td class="text-center"><a href="{% url "detail_patient_view" surgeon.emp_number %}">View Record</a></td>
                {% else %}
                    <td class="text-center"> No Record, <a href="{% url "staff_to_patient" surgeon.emp_number %}"> Add </a></td>
                {% endif %}            </div>
            </tr>
            {% endfor %}
        </table>

</div>
{% endblock %}

hospital/templates/medication_list.html
{% extends "base.html" %}
{% load static %}

{% block header %}
{{ header }}

{% endblock %}


{% block content %}
    {% for object in object_list %}
        <div class="list-group">
            <a href="{% url 'view_medications' object.id %}" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1 text-primary">{{ object.name }}</h5>
                <small>Available Quantity: {{ object.available_qnty }} </small>
            </div>
            <p class="mb-1">Code: {{ object.code }}</p>
            <small>{{ object.usage }}</small>
            <p class="mb-3"><u> Interacts with {{object.interactions_count}} medicines </u></p>
            </a>
        </div>
    {% endfor %}

{% endblock %}

hospital/templates/patient_detail.html
{% extends "base.html" %}
{% load static %}

{% block header %}
<h1>Patient: {{ object.first_name }} {{ object.last_name }}</h1>
{% endblock %}



{% block content %}
<div class="container row">
    <div class="col-sm-6">
        <table class="table">
            <tr>
                <td>First Name</td><td>{{ object.first_name }}</td>
            </tr>
            <tr>
                <td>Last Name</td><td>{{ object.last_name }}</td>
            </tr>
            <tr>
                <td>DOB</td><td>{{ object.dob }}</td>
            </tr>
            <tr>
                <td>Gender</td><td>{{ gender }}</td>
            </tr>
            <tr>
                <td>Address</td><td>{{ object.address }}</td>
            </tr>
            <tr>
                <td>Phone</td><td>{{ object.phone }}</td>
            </tr>
            <tr>
                <td>SSN</td><td>{{ object.ssn }}</td>
            </tr>
            <tr>
                <td>Primary Care Physician</td><td>{{ object.pcp }}</td>
            </tr>
            <tr>
                <td>Blood Type</td><td>{{ blood_type }}</td>
            </tr>
            <tr>
                <td>Blood Sugar</td><td>{{ object.blood_sugar }}</td>
            </tr>
            <tr>
                <td>Cholesterol HDL</td><td>{{ object.cholesterol_hdl }}</td>
            </tr>
            <tr>
                <td>Cholesterol LDL</td><td>{{ object.cholesterol_ldl}}</td>
            </tr>
            <tr>
                <td>Cholesterol Tri</td><td>{{ object.cholesterol_tri }}</td>
            </tr>
            {% if total_cholesterol > 0 %}
                <tr>
                    <td>Total Cholesterol</td><td>{{ total_cholesterol }}</td>
                </tr>
                <tr>
                    <td>Heart Disease Risk</td><td>{{ heart_risk }}</td>
                </tr>
            {% endif %}
            {% if object.admission_date %}
                <tr>
                    <td>Admission Date</td><td>{{ object.admission_date }}</td>
                </tr>
                <tr>
                    <td>Assigned Bed</td><td>{{ object.bed }}</td>
                </tr>
                <tr>
                    <td>Assigned Nurse</td><td>{{ object.assigned_nurse }}</td>
                </tr>
            {% endif %}

        </table>
    </div>
    <div class="col-sm-6">
        <h4>Allergies</h4>
        <ul>
            {% for allergy in object.allergies.all %}
            <li>{{ allergy.name }}</li>
            {% endfor %}
        </ul>
        <h4>Illnesses</h4>
        <ul>
            {% for illness in object.illnesses.all %}
            <li>{{ illness.name }}</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

hospital/templates/surgeon_detail.html
{% extends "base.html" %}
{% load static %}

{% block header %}
<h1>Surgeon: {{ object.first_name }} {{ object.last_name }}</h1>
{% endblock %}



{% block content %}
<div class="container row">
    <div class="col-sm-6">
        <table class="table">
            <tr>
                <td>First Name</td><td>{{ object.first_name }}</td>
            </tr>
            <tr>
                <td>Last Name</td><td>{{ object.last_name }}</td>
            </tr>
            <tr>
                <td>DOB</td><td>{{ object.dob }}</td>
            </tr>
            <tr>
                <td>Gender</td><td>{{ gender }}</td>
            </tr>
            <tr>
                <td>Address</td><td>{{ object.address }}</td>
            </tr>
            <tr>
                <td>Phone</td><td>{{ object.phone }}</td>
            </tr>
            <tr>
                <td>SSN</td><td>{{ object.ssn }}</td>
            </tr>

        </table>
    </div>
    <h2>Skills:</h2>
    <ul>

        {% for assignedskill in object.assignedskills_set.all %}
        <li>{{ assignedskill.skill }}</li>
        {% endfor %}
    </ul>

    <a href="{% url "add_skill_view" object.emp_number %}">Add Skill</a>

</div>
{% endblock %}